spring.application.name=investment-portfolio

# H2 in-memory database
spring.datasource.url=jdbc:h2:mem:investorsdb
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

# Let JPA auto-create tables from your @Entity classes
spring.jpa.hibernate.ddl-auto=update

# Enable the H2 web console at http://localhost:8080/h2-console
spring.h2.console.enabled=true